components/services/data/html.template, components/services/instances/html.template, components/types/local_def__Project/html.template, components/types/local_def__Project/queries/companies.query
Also fixes some stray html tags in instances
Centres and provides header for /data page
=> Makes links in project page to companies work

components/types/local_def__Company/html.template, components/types/local_def__Company/queries/countries.query, components/types/local_def__Company/queries/licenses.query, components/types/local_def__Company/queries/projects.query, components/types/local_def__Country/html.template, components/types/local_def__Country/queries/companies.query, components/types/local_def__Project/html.template, components/types/local_def__Project/queries/licenses.query
A number of commits to bring in linked data to default 'type' views - Project, Country, Company
Please review and see what you think
=> Improve type pages

components/types/local_def__License/html.template, components/types/local_def__License/queries/company.query, components/types/local_def__License/queries/countries.query, components/types/local_def__License/queries/licenses.query, components/types/local_def__License/queries/projects.query
Replaces the default triples view with a cleaner HTML page
Probably needs a bit more attention in terms of user need and what
information people really need
=> Adds a human readable license 'type' page

components/types/local_def__Company/html.template, components/types/local_def__License/html.template, components/types/local_def__Project/html.template
=> [#21] Fixes typo in table

components/types/local_def__Company/queries/licenses.query, components/types/local_def__Company/queries/projects.query
I'm having trouble recreating the problem locally, but following
documentation: http://www.w3.org/TR/rdf-sparql-query/#MultipleOptionals
this should make more data oprtional and result in no results.
Please review
=> [#24] Makes some data used in the templates optional

components/types/local_def__Company/html.template, components/types/local_def__Company/queries/payments.query, components/types/local_def__Company/queries/projects.query, components/types/local_def__Project/html.template, components/types/local_def__Project/queries/companies.query, components/types/local_def__Project/queries/licenses.query, components/types/local_def__Project/queries/main.query
While this is still a work in progress - with the new data model the existing front end shows very little, so it might be worth merging this in, because at least some things work in this branch
=> 32 rebuild frontend queries

components/includes/footer.inc, components/services/classes/html.template, components/services/data/html.template, components/services/default-view/html.template, components/services/instances/html.template, components/services/namedGraphs/html.template, components/services/search/html.template, components/services/testtest/html.template, components/static/css/nrgi.css, components/types/local_def__Company/html.template, components/types/local_def__Country/html.template, components/types/local_def__License/html.template, components/types/local_def__Project/html.template
Updates the css
Copies footer and some details from main website
=> [#25] Adds a footer to the site

components/services/data/html.template, components/services/data/queries/projects.query, components/types/local_def__Project/html.template, components/types/local_def__Project/queries/main.query
creates a table with country and commodity
=> [#32] Adds more detail to the projects overview page

components/types/local_def__Project/html.template, components/types/local_def__Project/queries/companies.query
Adds companies (back?) in
Gives Production Stats an id to check through on should you need
=> [#32] Cleans up Project page

components/services/data/html.template, components/services/data/queries/projects.query
Each Browse option needs configuring in the data/services main query
and template
=> [#32] Updates the front page links so that they all find an endpoint

components/includes/header.inc, components/static/css/nrgi.css
Proper wording needs to be agreed
=> [#30] Minor css and html changes to add a message at top of site

components/includes/pager.inc, components/services/data/html.template, components/services/data/queries/main.query, components/services/data/queries/projects.query, settings.inc.php
Needs debugging slightly, but tries to deal with previous links that
point to a negative offset. Does not yet deal with paging that goes
beyond the number of results
=> [#51] Adds some paging to company and project overview pages

components/static/about.html
Still needs to have agreed text added, but the method of adding
static pages can be copied from this - i.e. name them, and stick
them in componants/static
Puts a page at /about.html
=> [#14] Adds a static About page to the code base

components/types/local_def__Site/html.template
Found out how to do this my trial and error
=> [#50] Applies a default zoom to google maps

components/includes/header.inc, components/includes/pager.inc, components/services/company/html.template, components/services/company/json.template, components/services/company/queries/main.query, components/services/country/html.template, components/services/country/json.template, components/services/country/queries/commodities.query, components/services/country/queries/main.query, components/services/country/queries/projects.query, components/services/license/html.template, components/services/license/json.template, components/services/license/queries/main.query, components/services/project/html.template, components/services/project/json.template, components/services/project/queries/main.query
Leaves the data service in place so that we can continue to copy stuff
from there as we need it
Also provides a fix for the pager - whcih might not be the best fix
but seems to work
=> [#46] Sets up new services for project, company, country, license

components/includes/footer.inc, components/includes/header.inc, components/static/css/nrgi.css, components/static/js/bootstrap3-typeahead.js
But breaks the type ahead search facitlity
@Bjwebb Can you help me debug the typeahead issue pls
=> Adds table sorting to the application, and moves to bootstrap3

components/includes/advanced_links.inc, components/services/source/html.template, components/services/source/queries/main.query, components/static/css/nrgi.css, components/types/local_def__Company/html.template, components/types/local_def__CompanyPayment/html.template, components/types/local_def__Country/html.template, components/types/local_def__License/html.template, components/types/local_def__Project/html.template, components/types/local_def__Site/html.template, components/types/rdfs__Resource/html.template
Does some stuff so that you can click through to a 'source' page
=> 20 look up provenance

components/services/company/html.template, components/services/company/queries/main.query, components/services/project/html.template, components/services/project/queries/main.query, components/types/local_def__Company/html.template, components/types/local_def__Company/queries/countries.query
Includes three commits to update project listings to reflect new model, add company group to the company tables, and remove country duplicates on project pages.
@caprenter might want to check these out first? 
@Bjwebb Let me know if I've used right Git process here, or if I should work differently for further updates.
=> Query revisions

components/types/local_def__Country/html.template, components/types/local_def__Country/queries/companies.query, components/types/local_def__Country/queries/projects.query
Removes IDs from tables (except for payments)
Fixes broken commodities query for projects table
Removes duplicates of company names
=> [#16][#54] Tidies up the country page

components/services/group/html.template, components/services/group/json.template, components/services/group/queries/main.query, components/types/local_def__Group/html.template, components/types/local_def__Group/queries/company.query, components/types/local_def__Group/queries/countries.query, components/types/local_def__Group/queries/main.query, components/types/local_def__Group/queries/payments.query, components/types/local_def__Group/queries/projects.query
Needs some work on an individual group page still, but I think there
are some other queries to sort out first
=> [#85] Starts to add the group pages and list

components/types/local_def__Project/html.template, components/types/local_def__Project/queries/commodities.query, components/types/local_def__Project/queries/countries.query, components/types/local_def__Project/queries/payments.query
Tidies up the queries and seperates them
Adds payments to the page as these are now available in the model
=> [#17] Projects page - tidies up. Adds payments

components/services/country/queries/commodities.query, components/types/local_def__Company/queries/countries.query, components/types/local_def__Company/queries/projects.query, components/types/local_def__Country/queries/companies.query, components/types/local_def__Group/html.template, components/types/local_def__Group/queries/countries.query, components/types/local_def__Group/queries/payments.query, components/types/local_def__Group/queries/projects.query, components/types/local_def__Project/queries/companies.query
Now all the type pages should more or less pull project, company
and or payment data as required. If bugs are found they should be
reported seperately
=> [#97] Fixes hasStakeholding data bug

components/services/company/html.template, components/services/company/queries/main.query, components/services/group/html.template, components/services/group/queries/main.query
..but the numbers don't seem to add up properly
This is a feature request I guess, but needs work
=> Adds more counts to /group and /company

components/includes/pager.inc, components/services/company/html.template, components/services/company/queries/count.query, components/services/data/html.template, components/services/data/queries/count.query, components/services/project/html.template, components/services/project/queries/count.query
Problem we have here is that I can't seem to add offset to limit
anywhere to actually calculate anything.
Any ideas?
=> [#51] Adds experimental 'showing x to y of z records' to pager

components/services/company/html.template, components/services/group/html.template, components/static/css/nrgi.css
Simple bootstrap button - maybe a bit ugly, but does the job
=> [#86] Provides a toggle button on Companies and Groups pages

components/types/local_def__GovernmentReceipt/html.template, components/types/local_def__GovernmentReceipt/queries/payments.query
=> Finally adds government receipt pages!

components/types/local_def__Country/queries/projects.query
Needs careful checking before merging on Monday
=> 54 duplicates country page

components/types/local_def__Country/html.template, components/types/local_def__Country/queries/companies.query, components/types/local_def__Country/queries/main.query, components/types/local_def__Country/queries/projects.query
A few niggly improvements to make the data work, make the map work
and so on
=> Improve country  page

components/includes/default_map.js.inc, components/services/company/html.template, components/types/local_def__Country/html.template, components/types/local_def__Country/queries/sites.query, components/types/local_def__Project/html.template
Just committing this change while I remember. Following consultation we went with the ESRI map tiles. Other options remain in the default includes file should we change our minds
=> Fixes the default map to ESRI

components/includes/header.inc, components/services/company/html.template, components/types/local_def__Country/html.template, components/types/local_def__Country/queries/projects.query, components/types/local_def__Project/html.template, components/types/local_def__Project/queries/companies.query, components/types/local_def__Project/queries/main.query, components/types/local_def__Project/queries/sites.query, fts/test_fts.py
This is a whole bunch of fixes against #135
=> 135 key pages

fts/test_fts.py
This uses a mixture of parameterisation+fixtures and set comparisons.
For more information see https://github.com/NRGI/resourceprojects.org-frontend/pull/148#issuecomment-148449218
=> [#148] Faster tests, but still using parameterisation where appropirate

components/services/project/html.template, components/services/project/queries/main.query, fts/test_fts.py
Alters queries to populate missing data columns
=> Fixes missing data on projects list page

components/static/glossary.html, fts/test_fts.py
Adds tests for main headings only
=> [#158] Adds a glossary page

README.md
Just wanted to get something in there. You may want to improve what I have written. I'm happy for you to do that.
=> Adds some info about running the tests

components/includes/header.inc, components/static/css/nrgi.css, fts/test_fts.py
Adds a test
Squeezes the top nav a little to accomodate the new term
=> [#158] Puts the Glossary link in the navigation

components/static/index.html
Just not necessary. As requested by DavidM
=> [#15] Remove Jumbotron from front page

components/static/css/nrgi.css, components/types/local_def__Project/html.template, components/types/local_def__Project/queries/main.query, components/types/local_def__Project/queries/production_stats.query, components/types/local_def__Project/queries/status.query, fts/test_fts.py
Puts the productions stats table in correct order
Fetches status and commodity queries correctly
Puts project info into a table
Orders production stats by year
=> [#17] Improves the project page

components/static/css/nrgi.css, components/types/local_def__Project/html.template, fts/test_fts.py
Adds a location table to the project page - project info area
=> 17 project page design

components/types/local_def__Site/html.template, components/types/local_def__Site/queries/main.query, fts/test_fts.py
The sites page view may or may not be needed, but it is in here
at the moment and with a quick tidy up I think works for us.
It is easy enough to remove should we want to.
=> Tidies up a sites page view

components/types/local_def__Project/html.template
so, we add a link to the site page, using part ofthe identifier
=> [#17] If sites have no name the locations table is still built

components/types/local_def__Project/queries/payments.query
=> Projects Payment query was not running correctly

components/types/local_def__Project/html.template, fts/test_html.py
Not sure how to write a test for this tho...
=> [#175] Fixes missing div/footer bug

components/services/country/queries/main.query, components/types/local_def__Country/html.template, components/types/local_def__Country/queries/projects.query, fts/test_fts.py
The query was not returning all projects or counting companies
correctly. The two issues were entwined around the sub query.
=> [#189] Fixes a problem with the project table on a country page

components/types/local_def__Project/html.template, components/types/local_def__Project/queries/commodities.query, components/types/local_def__Project/queries/main.query, fts/test_fts.py
Also adds tests for this project info box
Note the payments query is stiff failing - see pull request 173
=> [#17] Adds a country line to the project info box

components/types/local_def__Company/html.template, components/types/local_def__Country/html.template, components/types/local_def__Project/html.template
Still missing the info about commodities, but otherwise this is good
Also does not touch the projects page map which has not been accepted yet
=> [#192] Alters the text in markers

components/types/local_def__Country/html.template, components/types/local_def__Country/queries/payments.query, fts/test_fts.py
Uses the column order from #188
Adds a download link for the CSV for payments
=> [#16] Makes data on payments show up

components/types/local_def__Country/html.template, components/types/local_def__Country/queries/payments.query, fts/test_fts.py
Updates payment table on Country page
Puts data in correct columns - fixing problem introduced in
652b20e
Speeds up test for download links
Adds in columun for Projects
=> 16 country page view

fts/fixtures/countries.ttl, fts/fixtures/test.ttl, fts/test_fts.py
The base Angola data used for the tests needed updating
Also updated the country data file
Fixed tests accordingly
Removed the 'sites' test as we no longer show or care about these
=> Updates the fixtures and the tests

.travis.yml, fts/fixtures/peru.ttl, fts/test_fts.py, run-tests-locally.sh
=> [#207] Updates the local test script

components/types/local_def__Company/html.template, fts/test_fts.py
This is the last item requested in the ticket
=> [#184] Adds a Country value to the info box

components/types/local_def__CompanyPayment/queries/payments.query
This is not a particularlt important page
I have not written a test as yet as I don't think it's very important
and I'm waiting for other tests to be merged etc
Leave the issue open to add a test later
=> [#211] Limits the query to 1

components/types/local_def__Country/html.template, fts/test_fts.py
See the comments on the issue.
The filters are just looking less and less useful with the data as
it is
=> [#142] Removes filters from the Country page

components/types/local_def__Company/html.template, components/types/local_def__Company/queries/payments.query, components/types/local_def__Project/html.template, components/types/local_def__Project/queries/payments.query, fts/fixtures/norwaytheil.ttl, fts/test_fts.py
Fixes up tables on project, company and country pages
Adds download csv links
Orders table columns
Removes some duplicate entries using the filter
Adds new fixture data to catch those problems
=> Various fixes to payment tables across the site

components/services/commodity/html.template, components/services/commodity/json.template, components/services/commodity/queries/main.query, components/types/local_def__Commodity/html.template, components/types/local_def__Commodity/queries/company.query, components/types/local_def__Commodity/queries/main.query, components/types/local_def__Commodity/queries/projects.query, components/types/local_def__Commodity/queries/sites.query, fts/test_fts.py
This is missing tests, and any navigation links right now, but it
seems to work ok
visit it at /commodity
=> [#135] Adds a commodity list and a single commodity page

components/static/css/nrgi.css, components/types/local_def__Group/html.template, components/types/local_def__Group/queries/payments.query, components/types/local_def__Group/queries/projects.query, components/types/local_def__Group/queries/sites.query, fts/test_fts.py
Adds an info box
Moves companies table to the right
Fixes missing data in payments and projects tables
Adds 'no data available' switch in template
Adds download links to CSVs
Adds tests for most of this
=> [#214] A number of improvements to a company group page

components/services/list-sources/html.template, components/services/list-sources/queries/main.query, components/services/source/html.template, components/services/source/queries/main.query, components/types/local_def__Source/html.template, components/types/local_def__Source/queries/main.query
This should:
* Update the sources table (from the top level nav link)
* Update the view of individual sources
* Update the list-sources service
Tested against local copy with Peru data in, but not against the full corpus.
=> Updating sources views

components/includes/header.inc, fts/test_fts.py
Renames Data Sources to Sources
Adds in Commodities link
=> [#223] [#225] Updates top nav

components/types/local_def__Company/html.template, fts/test_fts.py
Values were being pulled from the wrong querie
=> [#234] Makes sure data about websites and Open Corporates shows up

components/types/local_def__Project/html.template, components/types/local_def__Project/queries/production_stats.query, fts/test_fts.py
=> [#236] Adds commodity values to production stats tables

components/types/local_def__Group/queries/payments.query
I don't have the data to test.
Would appreciate if you tried this out for me
=> [#230] Adding DISTINCT seems to reduce the duplicates

components/types/local_def__Company/html.template, components/types/local_def__Country/html.template, components/types/local_def__Project/html.template
It's hard to write tests for all of the cases where every table is empty
Also there is a possibility I could bork the pages that have been edited
Exisiting tests pass for me, so I'm reasonably confident. All pages
altered here do have tests that would fail if the pages were broken
=> [#216] This adds 'if no data' checks to all the tables on single pages

components/types/local_def__Commodity/html.template, fts/test_html.py
Adds tests for this page and the commodities list to the tests
=> [#245] Fixes missing div

components/services/map/html.template, components/services/map/queries/sites.query, components/types/local_def__Commodity/html.template, components/types/local_def__Commodity/queries/sites.query, components/types/local_def__Company/html.template, components/types/local_def__Country/html.template, components/types/local_def__Group/html.template, components/types/local_def__Project/html.template
In addition I have removed some white space
NB Before merging it might be worth checking if this has any
effect on load times. I would expect more markers to be placed on
the map, but the same amount of HTML created
=> [#248] Fixes the templates to use site id in map markers

fts/test_fts.py
The Animon project is in the test fixture data with 1 company
On the live site there are no companies
I think it is a data issue, but this test, tests for it
=> [#244][#253] Adds a test to catch the bug in [#253]

components/types/local_def__Country/html.template
There was a html comment that was being written out time and time again
And some more white space that could be trimmed.
Targetting the country page specifically here, so mexico may load a little
faster. In fact it probably does not load faster, but it halves the amount
of data sent to the browser, and I think that less data to the leaflet.js
map also improves things client side.
=> [#251] Removes more uneccessary html from the country page

components/services/source/queries/main.query, components/types/local_def__Project/html.template, components/types/local_def__Project/queries/receipt.query, fts/fixtures/eiti-ph.ttl, fts/test_fts.py
[#259] Fixes the payments table on a project page
The query is altered thanks to @timdavies
Tests are in place to catch the previous errors, but in order to
do that I have had to add a new fixture and alter a couple of tests
that were affected by that.
Reference pages to test can be found via the test file or the issue
=> 259 government party over country

components/static/css/nrgi.css, fts/fixtures/eiti-ph.ttl, fts/test_fts.py
The style of the contract/concessions is updated
A test fixture datasetis replaced with an updated version
A test is given to check the fixture data is shown
=> [#265] Formats contracts and concessions, updates fixture, adds test
