components/types/local_def__Company/html.template
components/types/local_def__CompanyPayment/html.template
components/types/local_def__Country/html.template
components/types/local_def__Site/html.template

Although the full datetime string is availble and passed to the template
we use a template filter to format the date as a single year

[#36] Formates the date time as a year in the template

---

components/types/local_def__Company/html.template
components/types/local_def__Company/queries/group.query
components/types/local_def__Company/queries/payments.query
components/types/local_def__Company/queries/projects.query

Reduces some duplicates in projects and payments table - but not all
NOTE: There is a problem with some of the data so that queries for
project table return no results at the moment for EITI data
Turns payment id's into smaller strings

[#18] Improves company pages

---

components/types/local_def__Company/html.template
components/types/local_def__CompanyPayment/html.template
components/types/local_def__CompanyPayment/queries/payments.query
components/types/local_def__Country/html.template
components/types/local_def__Country/queries/payments.query
components/types/local_def__Group/html.template
components/types/local_def__Group/queries/payments.query
components/types/local_def__Project/html.template
components/types/local_def__Project/queries/payments.query

Removes commas from all values in payments tables on:
Group page, Project page, Company Page, Companypayment page,
Country page
Tables are uniform, except for where additions/ommisions are important
e.g. no need for an ID column on company payment pages
Column order is altered as suggested in #59
Type becomes Payment Type as suggested in #59

[#101][#59] Adjustments to payments table

---

components/types/local_def__Country/html.template
components/types/local_def__Group/html.template
components/types/local_def__Group/queries/payments.query
components/types/local_def__Project/html.template
components/types/local_def__Project/queries/payments.query

Makes sure tables have both paid by and paid to columns where needed
Makes sure when only one is required, it is the right one
i.e. companies page shows paid to, county page shows paid by
Adds a government receipt view to the application

[#117] Gets the right data in the tables

---

components/services/country/html.template
components/services/country/queries/commodities.query

Also removes ?name from the query as it isn't used and causes some
duplicates to be shown.

(& -> and) on country list page, so commodity counts are shown correctly

---

components/types/local_def__Company/html.template
components/types/local_def__Company/queries/payments.query
components/types/local_def__CompanyPayment/html.template
components/types/local_def__CompanyPayment/queries/payments.query
components/types/local_def__Country/html.template
components/types/local_def__Country/queries/payments.query
components/types/local_def__Group/html.template
components/types/local_def__Group/queries/payments.query
components/types/local_def__Project/html.template
components/types/local_def__Project/queries/payments.query

The desired left to right column is:
paid by, paid to, id, year, payment/receipt, payment type, currency, value
(We miss out some columns where they don't make sense)

[#59] Re-orders columns in payment tables

---

components/types/local_def__Project/queries/companies.query

Check the issue for links to pages to check out.
The amendment to the query uses a FILTER to block out empty 'share'
values. Without filter there are duplictes on the jubilee page.
Please evaluate carefully before accepting this

[#127] Should now show shares

---

components/services/company/queries/main.query

The stakeholder relationship should now be fixed in the data, so a correct query is here.
This change would also need applying to group.

Update project county query on company page

---

components/types/local_def__Project/html.template
components/types/local_def__Project/queries/alias.query
components/types/local_def__Project/queries/companies.query
components/types/local_def__Project/queries/main.query
fts/test_fts.py

This is an old issue, but has a new answer
The test changes the project page used.
Note that the url now seems to have AO instead of ao (caps)?
Test counts number of expected rows in company table

[#54] Removes duplicates from a the Companies table on a project page

---

components/types/local_def__Project/html.template
components/types/local_def__Project/queries/payments.query
components/types/local_def__Project/queries/receipt.query
fts/test_fts.py

Government receipts were not being picked up as payments associated
with projects
By adding another query we simply append rows to the existing table

[#17] Adds Government receipts to project payment table

---

components/types/local_def__Company/html.template
components/types/local_def__Country/html.template
components/types/local_def__Project/html.template

Projects and sites are linked from markers as appropriate
(Operator) place holder is removed

Map markers are now consistently rendered

---

components/types/local_def__Company/html.template
components/types/local_def__Company/queries/company.query
components/types/local_def__Company/queries/projects.query
fts/test_fts.py

Where payments data is missing we get a no data message
Projects table was not showing some data on some pages so the
query is made less demanding
The company info box is styled as a table and more data is shown

[#18] Companies page

---

components/services/map/html.template
components/services/map/queries/sites.query
fts/test_fts.py

The map on the projects list could be complemented or replaced by
a map at it's own page.
This has the advantage that page loads on the projects list should be
faster.
This change requires a docker rebuild to add the new service.
Tests for this page are minimal and juts test that the heading is there
I'm unsure how to better test for the map itself
I'm not sure how we would put this at e.g. project/map instead of at
/map

Adds a new service -  map

---

components/services/group/queries/main.query

Problem was old relationship with stakes
Also added the requirement that projects have names as a safeguard

[#217] Fixes the project counts in the comppany group list

---

components/services/commodity/html.template
components/services/commodity/queries/main.query
fts/test_fts.py

The query was not filtering to just projects in the count so
pulled in some extra sites
The tests should count the Bauxite projects in the Commodities page

[#231] Fixes the Bauxite counting bug

---

components/types/local_def__Country/html.template
components/types/local_def__Country/queries/commodities.query
components/types/local_def__Country/queries/companies.query
components/types/local_def__Country/queries/main.query
components/types/local_def__Country/queries/projects.query
components/types/local_def__Country/queries/sites.query
components/types/local_def__Country/queries/status.query

We have many queries that use optional clauses because we are not sure about what is in the data. I think these generally slow thingsdown.
Because we know more about the data, we can remove some of these because we know for example that projects without a name do not need to be shown.
The tweak to the sites query fixes a bug that improves load time on that query.
Splitting the commodities and status queries out of the project query I think improves things. 
Again with these queries we can now loose the optional elements, and require to return just one value (Projects are currently Oil and Gas OR Mining, and each only needs one status (even
if more are supplied they are duplicates)
I've split these out and then use a loop in the template to display the correct ones against the correct …

[#235] This might speed up country page load times

---

components/types/local_def__Project/queries/production_stats.query
fts/test_fts.py

Issue reported: https://github.com/NRGI/resource-projects-dataload/issues/21
The test data does not contain duplictes, so the test is not great
However the change works against a local copy of the latest data
and the query runs against a last live set of data

This removes duplicates in production stats table on project pages

---

components/services/list-sources/queries/main.query

We had left some hard-coded urls in the query. 
This is now replaced with  <{{lodspk.args.all|deurifier}}> and is working on my tests.

Fixes list-sources service - closes #228

---

components/services/source/html.template
fts/test_fts.py

Turns out this was a front-end issue due to the hangaa filter processing a blank value. 
I don't have a dev environment running right now so if @caprenter or @bjwebb can just check the addition of the if statements works, then this should close #232

Suggested fix for #232

---

components/services/map/queries/sites.query
components/types/local_def__Commodity/html.template
components/types/local_def__Commodity/queries/sites.query

Commodities like Gold have many map markers
The change to the query is similar to that done to a country page
I'm committing these so that we can test to see if this is an
optimisation or not for these pages. If so I can do to others

[#247] Optimises the sites query for /map and a commodity page

---

components/types/local_def__Project/html.template
components/types/local_def__Project/queries/concessions.query
components/types/local_def__Project/queries/contracts.query

With the updated ontology this allows a link to contracts (external URIs) and concessions (an unthemed internal page) to display on project pages.

183 concessions and contracts on project

---

components/services/project/json.template
components/services/project/queries/count.query
components/services/project/queries/main.query

At DataDive we looked at how ResourceContracts.org could search for project identifiers to match against when people are entering contracts.
I put together this quick examples of how we could do it with the RESTFul output of Project page, and, as a bonus, this gives us a search feature on the project page itself.

Adding project search

---

components/services/source/queries/main.query

Updating sources query to remove max-results restriction, remove retrievedDate (not used) and make explicit which fields distinct should be based upon.

Update sources query

---

components/types/local_def__Company/html.template

I'm unable to test this locally other than to see that a query is
now getting passed to the link, so I expect it to work

[#272] Alters the payments download csv
